export const PAGES_CODE = {
  HOME: 1 << 1,
  PROFILE: 1 << 2,
  DASHBOARD: 1 << 3,
  ADMIN: 1 << 4,
  SUPER_ADMIN: 1 << 5,
};

export const ROLES = {
  USER: PAGES_CODE.HOME + PAGES_CODE.PROFILE + PAGES_CODE.DASHBOARD,
  GUEST: PAGES_CODE.PROFILE + PAGES_CODE.SUPER_ADMIN,
  ADMIN:
    PAGES_CODE.HOME +
    PAGES_CODE.PROFILE +
    PAGES_CODE.DASHBOARD +
    PAGES_CODE.ADMIN,
  SUPER_ADMIN:
    PAGES_CODE.HOME +
    PAGES_CODE.PROFILE +
    PAGES_CODE.DASHBOARD +
    PAGES_CODE.ADMIN +
    PAGES_CODE.SUPER_ADMIN,
};

export const COMPONENT_CODE = {
  USER: 1 << 10,
  GUEST: 1 << 11,
  ADMIN: 1 << 12,
  SUPER_ADMIN: 1 << 13,
};

export const COMPONENT_ROLES = {
    USER: COMPONENT_CODE.USER,
    GUEST: COMPONENT_CODE.GUEST + COMPONENT_CODE.SUPER_ADMIN,
    ADMIN:
      COMPONENT_CODE.USER +
      COMPONENT_CODE.ADMIN,
    SUPER_ADMIN:
      COMPONENT_CODE.USER +
      COMPONENT_CODE.GUEST +
      COMPONENT_CODE.ADMIN +
      COMPONENT_CODE.SUPER_ADMIN,
  };
  
